package pojos;
// Generated May 4, 2020 3:16:56 PM by Hibernate Tools 4.3.1



/**
 * StuEmp generated by hbm2java
 */
public class StuEmp  implements java.io.Serializable {


     private int id;
     private String studentName;
     private String empSalary;

    public StuEmp() {
    }

	
    public StuEmp(int id) {
        this.id = id;
    }
    public StuEmp(int id, String studentName, String empSalary) {
       this.id = id;
       this.studentName = studentName;
       this.empSalary = empSalary;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getStudentName() {
        return this.studentName;
    }
    
    public void setStudentName(String studentName) {
        this.studentName = studentName;
    }
    public String getEmpSalary() {
        return this.empSalary;
    }
    
    public void setEmpSalary(String empSalary) {
        this.empSalary = empSalary;
    }

    



}


